#!/usr/bin/env bash
INSTALL_VERSION="1.0.0"

REPO_URL="${REPO_URL:-https://github.com/clint456/k2-printer-analytics.git}"
REPO_BRANCH="${REPO_BRANCH:-main}"
INSTALL_DIR="${INSTALL_DIR:-/opt/k2-analytics}"

MOONRAKER_HOST="${MOONRAKER_HOST:-192.168.1.146}"
MOONRAKER_PORT="${MOONRAKER_PORT:-7125}"
APP_PORT="${APP_PORT:-3000}"
API_PORT="${API_PORT:-8000}"
DB_PORT="${DB_PORT:-5432}"

DB_NAME="${DB_NAME:-k2_analytics}"
DB_USER="${DB_USER:-k2user}"
DB_PASS="${DB_PASS:-k2pass}"

ELECTRICITY_RATE="${ELECTRICITY_RATE:-0.49}"
CURRENCY="${CURRENCY:-AUD}"
TIMEZONE="${TIMEZONE:-Australia/Perth}"

MEROSS_EMAIL="${MEROSS_EMAIL:-}"
MEROSS_PASSWORD="${MEROSS_PASSWORD:-}"
MEROSS_DEVICE_NAME="${MEROSS_DEVICE_NAME:-Printer}"
MEROSS_DEVICE_UUID="${MEROSS_DEVICE_UUID:-}"

INSTALL_NPM="${INSTALL_NPM:-false}"
NPM_PORT="${NPM_PORT:-81}"
NPM_HTTP_PORT="${NPM_HTTP_PORT:-80}"
NPM_HTTPS_PORT="${NPM_HTTPS_PORT:-443}"

SELF_SIGNED_CERT="${SELF_SIGNED_CERT:-false}"
CERT_DOMAIN="${CERT_DOMAIN:-k2-analytics.local}"
CERT_DAYS="${CERT_DAYS:-365}"

DEFAULT_FILAMENT_COST="${DEFAULT_FILAMENT_COST:-24.0}"
FILAMENT_DENSITY_PLA="${FILAMENT_DENSITY_PLA:-1.24}"
FILAMENT_DENSITY_ABS="${FILAMENT_DENSITY_ABS:-1.04}"
FILAMENT_DENSITY_PETG="${FILAMENT_DENSITY_PETG:-1.27}"
FILAMENT_DENSITY_TPU="${FILAMENT_DENSITY_TPU:-1.21}"
FILAMENT_DIAMETER="${FILAMENT_DIAMETER:-1.75}"